name: shoping
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6
  flutter_card_swiper: ^2.0.0
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0

  image_compare_slider: ^2.8.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
#   recommended
   - assets/images/recommended/1.jfif
   - assets/images/recommended/2.jpg
   - assets/images/recommended/3.jfif
   - assets/images/recommended/4.jpg
   - assets/images/recommended/5.jpg
   - assets/images/recommended/6.jpg
   - assets/images/recommended/7.jpg
   - assets/images/recommended/8.jfif
   - assets/images/recommended/9.png
   - assets/images/recommended/10.jfif
   - assets/images/recommended/11.jpg
   - assets/images/recommended/12.jpg
   - assets/images/recommended/13.webp
   - assets/images/recommended/14.jpg
   - assets/images/recommended/15.jpg
   - assets/images/recommended/16.webp
   - assets/images/recommended/17.jfif
   - assets/images/recommended/18.jpg
   - assets/images/recommended/19.jpg
   - assets/images/recommended/20.jpg
   - assets/images/recommended/21.jpg
   - assets/images/recommended/22.jfif
   - assets/images/recommended/23.jpg
   - assets/images/recommended/24.jpg
   - assets/images/recommended/25.jpg
   - assets/images/recommended/26.jpg

#   popular
   - assets/images/popular/1.jfif
   - assets/images/popular/2.jpg
   - assets/images/popular/3.jpg
   - assets/images/popular/4.jfif
   - assets/images/popular/5.webp

#   bookMarked
   - assets/images/bookmarked/1.jpg
   - assets/images/bookmarked/2.jfif
   - assets/images/bookmarked/3.webp
   - assets/images/bookmarked/4.gif
   - assets/images/bookmarked/5.jpg

#   bookMarked
   - assets/images/category/가디건.jpg
   - assets/images/category/블라우스.jpg
   - assets/images/category/셔츠.jpg
   - assets/images/category/자켓.jpg
   - assets/images/category/청바지.jpg
   - assets/images/category/치마.jpg
   - assets/images/category/코트.jpg
   - assets/images/category/티셔츠.webp

#   cart
   - assets/images/cart/1.jpg
   - assets/images/cart/2.png
   - assets/images/cart/3.jpg
   - assets/images/cart/4.jpg
   - assets/images/cart/5.jpg

#   user
   - assets/images/user/1.jpg
   - assets/images/user/2.png

#   intro
   - assets/images/intro_image.png

#   icons
   - assets/icons/cart.png
   - assets/icons/full_heart.png
   - assets/icons/heart.png
   - assets/icons/heart_red.png
   - assets/icons/home.png
   - assets/icons/profile.png
   - assets/icons/menu.png
   - assets/icons/drawer_menu.png
   - assets/icons/search.png
   - assets/icons/clock.png
   - assets/icons/delete.png

#     font image
   - assets/images/front.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
#     - family: Nanum Pen
#       fonts:
#         - asset: fonst/NanumPen.ttf
#     - family: Nerko One
#       fonts:
#          - asset: fonts/NerkoOne-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
